version: '3.0'

services:
  grafana:
    container_name: 'esnet-networkmap-panel'
    build:
      context: ./.config
      args:
        grafana_version: '10.4.0'
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/esnet-networkmap-panel
      - ./provisioning:/etc/grafana/provisioning
