services:
  grafana:
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
    container_name: 'esnet-networkmap-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.4.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/esnet-networkmap-panel
      - ./provisioning:/etc/grafana/provisioning
