type inputTypes = 'json' | 'url';

export interface MapOptions {
  color1: string;
  color2: string;
  color3: string;
  layer1: boolean;
  mapjsonL1: string;
  nodeHighlightL1: string;
  srcFieldL1: string;
  dstFieldL1: string;
  valFieldL1: string;
  endpointIdL1: string;
  layer2: boolean;
  mapjsonL2: string;
  nodeHighlightL2: string;
  srcFieldL2: string;
  dstFieldL2: string;
  valFieldL2: string;
  endpointIdL2: string;
  layer3: boolean;
  mapjsonL3: string;
  nodeHighlightL3: string;
  srcFieldL3: string;
  dstFieldL3: string;
  valFieldL3: string;
  endpointIdL3: string;
  startLat: number;
  startLng: number;
  startZoom: number;
  editMode: boolean;
  legendL1: boolean;
  legendL2: boolean;
  legendL3: boolean;
  layerName1: string;
  layerName2: string;
  layerName3: string;
  nodeWidth: number;
  edgeWidth: number;
  pathOffset: number;
  inputL1: inputTypes;
  inputL2: inputTypes;
  inputL3: inputTypes;
  urlL1: string;
  urlL2: string;
  urlL3: string;

  // nodeWidthL1: number;
  // edgeWidthL1: number;
  // pathOffsetL1: number;
  // nodeWidthL2: number;
  // edgeWidthL2: number;
  // pathOffsetL2: number;
  // nodeWidthL3: number;
  // edgeWidthL3: number;
  // pathOffsetL3: number;
}
